import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import Computer from '../components/sections/Computer'
import Hero from '../components/sections/Hero'
import Technos from '../components/sections/Technos'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero/>
        <Computer/>
        <Technos/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
